name: radiation
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy=1.19.2
  - scipy=1.6.0
  - xarray=0.16.2
  - pandas=1.2.1
  - netcdf4=1.5.3
  - matplotlib=3.3.2
  - seaborn=0.11.1
  - pip
  - pip:
    - notebook==6.2.0
    - tensorflow==2.4.1
    - scikit-learn==0.24.1
    - pyvinecopulib==0.5.5
    - synthia==0.3.0
    - plotly==4.14.3