name: radiation
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - xarray
  - pandas
  - netcdf4
  - matplotlib
  - seaborn
  - jupyterlab
  - plotly
  - tensorflow
  - pip
  - pip:
    - pyvinecopulib
    - synthia
